apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-webhook
  labels:
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    external-secrets.io/component: webhook
