apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server-metrics
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: "argocd-server-metrics"
