apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-monitor.workflow-controller-metrics.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "argo-workflow"
  includeSelectors: false
