apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workflow-controller-metrics
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: "workflow-controller"
