apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- rbac.yaml
- service.yaml

namespace: kube-system
commonLabels:
  app.kubernetes.io/part-of: "kubernetes-external-secrets"

images:
- name: "ghcr.io/external-secrets/kubernetes-external-secrets"
  newTag: "8.5.0"
