apiVersion: v1
kind: Service
metadata:
  name: kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: "kubernetes-external-secrets"
spec:
  selector:
    app.kubernetes.io/name: "kubernetes-external-secrets"
  ports:
  - name: prometheus
    protocol: TCP
    port: 3001
    targetPort: prometheus
