apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-controller
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
rules:
- apiGroups:
  - "external-secrets.io"
  resources:
  - "secretstores"
  - "clustersecretstores"
  - "externalsecrets"
  - "clusterexternalsecrets"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "external-secrets.io"
  resources:
  - "externalsecrets"
  - "externalsecrets/status"
  - "externalsecrets/finalizers"
  - "secretstores"
  - "secretstores/status"
  - "secretstores/finalizers"
  - "clustersecretstores"
  - "clustersecretstores/status"
  - "clustersecretstores/finalizers"
  - "clusterexternalsecrets"
  - "clusterexternalsecrets/status"
  - "clusterexternalsecrets/finalizers"
  verbs:
  - "update"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "delete"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "serviceaccounts/token"
  verbs:
  - "create"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
- apiGroups:
  - "external-secrets.io"
  resources:
  - "externalsecrets"
  verbs:
  - "create"
  - "update"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-view
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - "external-secrets.io"
  resources:
  - "externalsecrets"
  - "secretstores"
  - "clustersecretstores"
  verbs:
  - "get"
  - "watch"
  - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-edit
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - "external-secrets.io"
  resources:
  - "externalsecrets"
  - "secretstores"
  - "clustersecretstores"
  verbs:
  - "create"
  - "delete"
  - "deletecollection"
  - "patch"
  - "update"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-controller
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
- name: external-secrets
  kind: ServiceAccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-leaderelection
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  resourceNames:
  - "external-secrets-controller"
  verbs:
  - "get"
  - "update"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "create"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-leaderelection
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-leaderelection
subjects:
- kind: ServiceAccount
  name: external-secrets
