apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- rbac.yaml

namespace: kube-system

images:
- name: "quay.io/reactiveops/rbac-manager:v1"
  newTag: "v1"
