apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

configMapGenerator:
- name: gatus-config
  files:
  - config.yaml=files/config.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "gatus"
    app.kubernetes.io/version: "v5.14.0"
  includeTemplates: true


images:
- name: "twinproduction/gatus"
  newTag: "v5.14.0"
