apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  labels:
    app.kubernetes.io/name: "dashy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "dashy"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "dashy"
    spec:
      serviceAccountName: dashy
      containers:
      - name: dashy
        image: lissy93/dashy:3.1.0
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        startupProbe:
          exec:
            command:
            - yarn
            - health-check
          failureThreshold: 3
          timeoutSeconds: 10
          periodSeconds: 90
          initialDelaySeconds: 40
        livenessProbe:
          exec:
            command:
            - yarn
            - health-check
          failureThreshold: 3
          timeoutSeconds: 10
          periodSeconds: 90
        # readinessProbe:
        #   httpGet:
        #     port: http
        #     scheme: HTTP
        #   failureThreshold: 3
        #   timeoutSeconds: 10
        #   periodSeconds: 90
        volumeMounts:
        - mountPath: /app/public/conf.yaml
          # readOnly: true
          name: dashy-config
          subPath: conf.yaml
      volumes:
      - name: dashy-config
        configMap:
          name: dashy-config
          defaultMode: 0640
