apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

configMapGenerator:
- name: dashy-config
  files:
  - conf.yaml=files/conf.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "dashy"
    app.kubernetes.io/version: "3.1.0"
  includeTemplates: true


images:
- name: "lissy93/dashy"
  newTag: "3.1.0"
