apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
# components:
# - ../../../../components/init-workloads

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "argo-workflow"
    app.kubernetes.io/version: "v3.1.1"
  includeTemplates: true

images:
- name: "docker.io/argoproj/argocli"
  newTag: "v3.1.1"
- name: "docker.io/argoproj/workflow-controller"
  newTag: "v3.1.1"
- name: "docker.io/argoproj/argoexec"
  newTag: "v3.1.1"
