apiVersion: v1
kind: Service
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/name: "miniflux"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: "miniflux"
