apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-external-secrets-controller
  labels:
    app.kubernetes.io/name: "kubernetes-external-secrets"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "kubernetes-external-secrets"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "kubernetes-external-secrets"
    spec:
      serviceAccountName: kubernetes-external-secrets
      containers:
      - name: kubernetes-external-secrets
        image: "ghcr.io/external-secrets/kubernetes-external-secrets:8.2.3"
        ports:
        - name: prometheus
          containerPort: 3001
        imagePullPolicy: IfNotPresent
        resources:
          {}
        env:
        - name: "AWS_DEFAULT_REGION"
          value: "ap-norhteast-2"
        - name: "AWS_REGION"
          value: "ap-northeast-2"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "LOG_MESSAGE_KEY"
          value: "msg"
        - name: "METRICS_PORT"
          value: "3001"
        - name: "POLLER_INTERVAL_MILLISECONDS"
          value: "10000"
        - name: "VAULT_ADDR"
          value: "http://127.0.0.1:8200"
        - name: "WATCH_TIMEOUT"
          value: "60000"
      securityContext:
        runAsNonRoot: true
